name: test tdd
on: [push]
jobs:
  test-tdd-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          yarn-version: '1.22.15'
      - run: yarn install
      - run: yarn test